sudo: required
language: node_js
node_js:
  - '6'
services:
  - rabbitmq
before_install:
- npm install --global yarn
install:
- yarn install
script:
  - echo "AMQP tests do not work"
before_script:
  - sudo rabbitmq-plugins enable rabbitmq_amqp1_0
  - sudo rabbitmqctl add_user meshblu judgementday
  - sudo rabbitmqctl set_permissions meshblu ".*" ".*" ".*"
  - sudo rabbitmqctl add_user some-uuid some-token
  - >-
    sudo rabbitmqctl set_permissions some-uuid
    '^(amq\.gen.*|amq\.default|^some-uuid.*)$' '.*' '.*'
  - sudo rabbitmqctl add_user a-new-uuid lol-a-token
  - >-
    sudo rabbitmqctl set_permissions a-new-uuid
    '^(amq\.gen.*|amq\.default|^a-new-uuid.*)$' '.*' '.*'
after_success:
  - yarn coverage
  - 'yarn mocha:json'
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'bash <(curl -s https://codecov.octoblu.com/bash)'
branches:
  only:
    - '/^v[0-9]/'
notifications:
  webhooks:
    - 'https://beekeeper.octoblu.com/webhooks/travis:ci'
