sudo: required
language: node_js
node_js:
  - '6'
services:
  - rabbitmq
addons:
  code_climate:
    repo_token: 919f23005f215de7e74cf0af258aba3a242cc64684810f7151ad6a26172caba5
before_script:
  - npm install -g codeclimate-test-reporter
  - sudo rabbitmq-plugins enable rabbitmq_amqp1_0
  - sudo rabbitmqctl add_user meshblu judgementday
  - sudo rabbitmqctl set_permissions meshblu ".*" ".*" ".*"
  - sudo rabbitmqctl add_user some-uuid some-token
  - >-
    sudo rabbitmqctl set_permissions some-uuid
    '^(amq\.gen.*|amq\.default|^some-uuid.*)$' '.*' '.*'
  - sudo rabbitmqctl add_user a-new-uuid lol-a-token
  - >-
    sudo rabbitmqctl set_permissions a-new-uuid
    '^(amq\.gen.*|amq\.default|^a-new-uuid.*)$' '.*' '.*'
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
after_success:
  - npm run coverage
  - 'npm run mocha:json'
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'bash <(curl -s https://codecov.octoblu.com/bash)'
branches:
  only:
    - '/^v[0-9]/'
notifications:
  webhooks:
    - 'https://beekeeper.octoblu.com/webhooks/travis:ci'
